#!/bin/bash
##
## MATLAB submission script for PBS on CR2 
## ------------------------------------------
##
##"MATLAB-sub2022v1"
## Follow the 6 steps below to configure your job
## 
## STEP 1:
##
## Enter a job name after the -N on the lin/e below:
##
#PBS -N RNA-Seq-Alignment_STAR_s411309
##
## STEP 2:
##
## Select the number of cpus/cores required by modifying the #PBS -l select line below
##
## Normally you select cpus in chunks of 16 cpus
## The Maximum value for ncpus is 16 and mpiprocs MUST be the same value as ncpus.
##
## PLEASE NOTE
## ===========
## The standard matlab application does not run on more than one node
## This select line must not be altered
##
#PBS -l select=1:ncpus=8:mpiprocs=8
##
## STEP 3:
##
## Select the correct queue by modifying the #PBS -q line below
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q six_hour
##
## STEP 4:
##
## Replace the hpc@cranfield.ac.uk email address
## with your Cranfield email address on the #PBS -M line below:
## Your email address is NOT your username
##
#PBS -m abe 
#PBS -M khalidadam.yusuf.309@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## STEP 5: 
## 
## Load the production USE
module use /apps2/modules/all 

#Q1. QC: quality score of >20% was observed
########################################################

#Q2. Read Alignment
####(a) Aligner 1 STAR
### Creating genome index for star
######## Load module STAR #################
module load STAR
##Creating directory for genomeIndex
mkdir -p /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/

STAR --runMode genomeGenerate \
--genomeDir /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--genomeFastaFiles \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang.fasta \
--sjdbGTFfile \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100

## Aligning the reads using STAR
###########################################
#B009951
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B009951_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B009951_2_paired.fq.gz \
--outFileNamePrefix B009951
#B009952
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B009952_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B009952_2_paired.fq.gz \
--outFileNamePrefix B009952
#B009953
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B009953_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B009953_2_paired.fq.gz \
--outFileNamePrefix B009953
#B50981
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50981_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50981_2_paired.fq.gz \
--outFileNamePrefix B50981
#B50982
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50982_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50982_2_paired.fq.gz \
--outFileNamePrefix B50982
#B50983
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50983_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50983_2_paired.fq.gz \
--outFileNamePrefix B50983
#B50995s1
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50995s1_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50995s1_2_paired.fq.gz \
--outFileNamePrefix B50995s1
#B50995s2
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50995s2_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50995s2_2_paired.fq.gz \
--outFileNamePrefix B50995s2
#B50995s3
STAR --runThreadN 8 --genomeDir ~/I-BIX-NGS_dataForAssignment_flang/genomeIndex_star/ \
--sjdbGTFfile /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/flang_gene_models_AUGUSTUS.gff \
--sjdbGTFfeatureExon CDS \
--sjdbGTFtagExonParentTranscript transcript_id \
--sjdbOverhang 100 --outSAMtype BAM SortedByCoordinate \
--readFilesCommand zcat --readFilesIn \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50995s3_1_paired.fq.gz \
/mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/trimmedReads/B50995s3_2_paired.fq.gz \
--outFileNamePrefix B50995s3

## Move BAM files together in the BAM folder inside the RNA-Seq_fruitFly directory

##Move STAR log files to their designated folders

##########################################################
##5. Perform read counts on the bam files using HTSeq
## Make sure you use other gff parameters if your annotation file
## doesn't have the default values (i.e. -i , -t, --additional-attr).
## https://htseq.readthedocs.io/en/release_0.11.1/count.html
##########################################################


##Make directory for HTSeq

 ## You can either do it for each sample individually or create a for loop to do it iteratively

#########################################################
##6. Differential expression and dowstream analysis can be 
##   performed directly on R
###########################################################


## Tidy up the log directory


##
## STEP 6: 
## 
## Put the correct parameters in the matlab execution line
## below to run MATLAB
## Unless you are sure do not change the default parameters
##
## The main parameters to modify is the input filename - change example.m to your own filename


## Tidy up the log directory
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
