#!/bin/bash
##
## MATLAB submission script for PBS on CR2 
## ------------------------------------------
##
##"MATLAB-sub2022v1"
## Follow the 6 steps below to configure your job
## 
## STEP 1:
##
## Enter a job name after the -N on the line below:
##
#PBS -N RNA-Practical_YOUR_USERNAME
##
## STEP 2:
##
## Select the number of cpus/cores required by modifying the #PBS -l select line below
##
## Normally you select cpus in chunks of 16 cpus
## The Maximum value for ncpus is 16 and mpiprocs MUST be the same value as ncpus.
##
## PLEASE NOTE
## ===========
## The standard matlab application does not run on more than one node
## This select line must not be altered
##
#PBS -l select=1:ncpus=8:mpiprocs=8
##
## STEP 3:
##
## Select the correct queue by modifying the #PBS -q line below
##
## half_hour	-  30 minutes
## one_hour	-   1 hour
## three_hour   -   3 hours
## six_hour     -   6 hours
## half_day	-  12 hours
## one_day	-  24 hours
## two_day	-  48 hours
## five_day	- 120 hours
## ten_day	- 240 hours (by special arrangement)
##
#PBS -q six_hour
##
## STEP 4:
##
## Replace the hpc@cranfield.ac.uk email address
## with your Cranfield email address on the #PBS -M line below:
## Your email address is NOT your username
##
#PBS -m abe 
#PBS -M khalidadam.yusuf.309@cranfield.ac.uk
##
## ====================================
## DO NOT CHANGE THE LINES BETWEEN HERE
## ====================================
#PBS -l application=matlab
#PBS -j oe
#PBS -W sandbox=PRIVATE
#PBS -k n
ln -s $PWD $PBS_O_WORKDIR/$PBS_JOBID
## Change to working directory
cd $PBS_O_WORKDIR
## Calculate number of CPUs
export cpus=`cat $PBS_NODEFILE | wc -l`
## ========
## AND HERE
## ========
##
## STEP 5: 
## 
## Load the production USE
module use /apps2/modules/all 

#Q1. QC: quality score of >20% was observed
########################################################
## 2. Performing read filtration using Trimommatic to balance forward and reverse reads
########################################################
## Load module Trimmomatic
module load Trimmomatic

## Applying loop to trim all reads in the raw_reads file
for f1 in /mnt/beegfs/home/s411309/I-BIX-NGS_dataForAssignment_flang/rawReads/*1.fq.gz
do

#only store the sample name as f2 variable, by removing R1.fastq
f2="${f1%%1.fq.gz}"

java -jar $EBROOTTRIMMOMATIC/trimmomatic-0.39.jar PE -phred33 $f2"1.fq.gz" $f2"2.fq.gz" $f2"1_paired.fq.gz" $f2"1_unpaired.fq.gz" \
$f2"2_paired.fq.gz" $f2"2_unpaired.fq.gz" \
ILLUMINACLIP:/apps2/software/Trimmomatic/0.39-Java-17/adapters/TruSeq3-PE.fa:2:30:10 \
LEADING:3 TRAILING:3 SLIDINGWINDOW:4:15 MINLEN:36

done

#Q2. Read Alignment
####(a) Aligner 1 STAR
### Creating genome index for star
######## Load module STAR #################

##Creating directory for genomeIndex

## Aligning the reads using STAR
###################################
## Move BAM files together in the BAM folder inside the RNA-Seq_fruitFly directory

##Move STAR log files to their designated folders

##(b) Aligner 2 BWA (Burrows_Wheeler Aligner)
###loading BWA module#########
#module use /apps2/modules/all

##indexing the reference genome using BWA

##Mapping the reads using BWA

##Converting SAM file into binary BAM file

##########################################################
##5. Perform read counts on the bam files using HTSeq
## Make sure you use other gff parameters if your annotation file
## doesn't have the default values (i.e. -i , -t, --additional-attr).
## https://htseq.readthedocs.io/en/release_0.11.1/count.html
##########################################################


##Make directory for HTSeq

 ## You can either do it for each sample individually or create a for loop to do it iteratively

#########################################################
##6. Differential expression and dowstream analysis can be 
##   performed directly on R
###########################################################


## Tidy up the log directory


##
## STEP 6: 
## 
## Put the correct parameters in the matlab execution line
## below to run MATLAB
## Unless you are sure do not change the default parameters
##
## The main parameters to modify is the input filename - change example.m to your own filename


## Tidy up the log directory
## DO NOT CHANGE THE LINE BELOW
## ============================
rm $PBS_O_WORKDIR/$PBS_JOBID
#
